# backend/FUNIT/configs/funit_handwriting.yaml

# ─── Logger 옵션 ────────────────────────────────────────────
image_save_iter:    2500
image_display_iter: 100
snapshot_save_iter: 5000
log_iter:           1

# ─── 최적화 옵션 ────────────────────────────────────────────
max_iter:      100000
weight_decay:  0.0001
lr_gen:        0.0001
lr_dis:        0.0001
init:          kaiming
gan_w:         1
fm_w:          1
r_w:           0.1

# ─── 모델 옵션 ──────────────────────────────────────────────
gen:
  nf:              64
  n_res_blks:      2
  nf_mlp:          256
  latent_dim:      64
  n_mlp_blks:      3
  n_downs_content: 3
  n_downs_class:   4

dis:
  nf:          64
  n_res_blks:  10
  num_classes: 2

# ─── 데이터 옵션 ────────────────────────────────────────────
num_workers:       4
batch_size:        16
new_size:          256
crop_image_height: 256
crop_image_width:  256

# ─── A 도메인 (폰트 스켈레톤) ─────────────────────────────────
data_folder_train: "../data/hand/A"
data_list_train:   "../data/hand/train_A.txt"

data_folder_test:  "../data/hand/A"
data_list_test:    "../data/hand/test_A.txt"

# ─── B 도메인 (실제 손글씨 스타일) ────────────────────────────
# FUNIT 의 get_train_loaders() 에서는
#   content ← data_folder_train / data_list_train
#   style   ← data_folder_train_class / data_list_train_class
# 의 쌍을 사용합니다.
data_folder_train_class: "../data/hand"
data_list_train_class:   "../data/hand/train_user.txt"

data_folder_test_class:  "../data/hand"
data_list_test_class:    "../data/hand/test_user.txt"
