# ─── Logger 옵션 ────────────────────────────────────────────
image_save_iter:    2500
image_display_iter: 100
snapshot_save_iter: 5000
log_iter:           1

# ─── 최적화 옵션 ────────────────────────────────────────────
max_iter:      200
weight_decay:  0.0001
lr_gen:        0.0001
lr_dis:        0.0001
init:          kaiming
gan_w:         1
fm_w:          1
r_w:           0.1

# ─── 모델 옵션 ──────────────────────────────────────────────
gen:
  nf:              64
  n_res_blks:      2
  nf_mlp:          256
  latent_dim:      64
  n_mlp_blks:      3
  n_downs_content: 3
  n_downs_class:   4

dis:
  nf:          64
  n_res_blks:  10
  num_classes: 2    # A vs user 두 개 도메인

# ─── 데이터 옵션 ────────────────────────────────────────────
num_workers:       4      # ← 반드시 추가
batch_size:        32
new_size:          128
crop_image_height: 128
crop_image_width:  128

# Content loader (A)
data_folder_train:       "../data/hand/A"
data_list_train:         "../data/hand/train_A.txt"
data_folder_test:        "../data/hand/A"
data_list_test:          "../data/hand/train_A.txt"  # A는 테스트 없이 전부 훈련

# Style loader (A+B merged)
data_folder_train_class: "../data/hand"
data_list_train_class:   "../data/hand/train_AB.txt"
data_folder_test_class:  "../data/hand"
data_list_test_class:    "../data/hand/test_AB.txt"